name: cursor-fuzzy-time-gen
version: '0.1.0.0'
category: Time
author: Tom Sydney Kerckhove
maintainer: syd@cs-syd.eu
copyright: ! 'Copyright: (c) 2017-2021 Tom Sydney Kerckhove'
license: MIT
homepage: https://github.com/NorfairKing/fuzzy-time
description: Generators for the fuzzy time cursors

extra-source-files:
- CHANGELOG.md

dependencies:
- base >=4.9 && <=5

library:
  source-dirs: src/
  ghc-options: -Wall
  dependencies:
  - containers
  - cursor-fuzzy-time
  - cursor-gen
  - deepseq
  - fuzzy-time
  - fuzzy-time-gen
  - genvalidity
  - genvalidity-time
  - megaparsec
  - time

tests:
  cursor-fuzzy-time-test:
    main: Spec.hs
    source-dirs: test/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - QuickCheck
    - cursor-fuzzy-time
    - cursor-fuzzy-time-gen
    - fuzzy-time
    - genvalidity
    - genvalidity-hspec
    - genvalidity-hspec-optics
    - genvalidity-time
    - hspec
    - megaparsec
    - text
    - time

benchmarks:
  cursor-fuzzy-time-bench:
    main: Bench.hs
    source-dirs: bench/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - QuickCheck
    - cursor-fuzzy-time
    - cursor-fuzzy-time-gen
    - genvalidity-criterion
    - criterion
