resolver: lts-23.19
packages:
- cursor-fuzzy-time
- cursor-fuzzy-time-gen

extra-deps:
- github: NorfairKing/fuzzy-time
  commit: c05c5d9ac6d7c1890ae3168efc3838814e1b538b
  subdirs:
  - fuzzy-time
  - fuzzy-time-gen

system-ghc: true
nix:
  enable: false
with-hpack: hpack
