resolver: lts-20.25
packages:
- cursor-fuzzy-time
- cursor-fuzzy-time-gen
extra-deps:
- github: NorfairKing/fuzzy-time
  commit: a1c1d07a861ad984ed5b0fe6f5da74f373e814e6
  subdirs:
  - fuzzy-time
  - fuzzy-time-gen
- github: NorfairKing/cursor
  commit: ae8727c0109d0706019413b36095b50541f37e5a
  subdirs:
  - cursor
  - cursor-gen
- github: NorfairKing/validity
  commit: 20ddbd625304817694b7ae9dc8751f7456259dd6
  subdirs:
  - genvalidity
  - genvalidity-aeson
  - genvalidity-bytestring
  - genvalidity-containers
  - genvalidity-criterion
  - genvalidity-hspec
  - genvalidity-hspec-aeson
  - genvalidity-hspec-binary
  - genvalidity-hspec-cereal
  - genvalidity-hspec-hashable
  - genvalidity-hspec-optics
  - genvalidity-path
  - genvalidity-property
  - genvalidity-scientific
  - genvalidity-text
  - genvalidity-time
  - genvalidity-unordered-containers
  - genvalidity-uuid
  - genvalidity-vector
  - validity
  - validity-aeson
  - validity-bytestring
  - validity-containers
  - validity-path
  - validity-primitive
  - validity-scientific
  - validity-text
  - validity-time
  - validity-unordered-containers
  - validity-uuid
  - validity-vector

system-ghc: true
nix:
  enable: false
with-hpack: hpack
