name:                cursor-fuzzy-time-demo
version:             0.0.0.0
github:              "NorfairKing/picosmos"
license:             AllRightsReserved
author:              "Tom Sydney Kerckhove"
maintainer:          "syd@cs-syd.eu"
copyright:           "Copyright: (c) 2018 Tom Sydney Kerckhove"

description:         Please see the README on GitHub at <https://github.com/NorfairKing/cursor-fuzzy-time#readme>


library:
  source-dirs: src
  dependencies:
  - base >= 4.7 && < 5
  - brick
  - cursor
  - cursor-fuzzy-time
  - directory
  - microlens
  - text
  - time
  - vty

executables:
  cursor-fuzzy-time-demo:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base >= 4.7 && < 5
    - cursor-fuzzy-time-demo
